return {
    'nvim-treesitter/nvim-treesitter',
    branch = 'main',
    build = ':TSUpdate',
    event = {
        'BufReadPost',
        'BufNewFile',
    },
    config = function()
        local treesitter = require('nvim-treesitter')
        treesitter.install({
            'asm',
            'bash',
            'blade',
            'c',
            'c_sharp',
            'cmake',
            'comment',
            'cpp',
            'css',
            'csv',
            'dart',
            'diff',
            'dockerfile',
            'doxygen',
            'editorconfig',
            'fsharp',
            'git_config',
            'git_rebase',
            'gitattributes',
            'gitcommit',
            'gitignore',
            'glsl',
            'go',
            'gomod',
            'gosum',
            'gotmpl',
            'gowork',
            'helm',
            'hlsl',
            'html',
            'html_tags',
            'htmldjango',
            'http',
            'hyprlang',
            'java',
            'javascript',
            'json',
            'json5',
            'jsx',
            'kotlin',
            'latex',
            'lua',
            'markdown',
            'markdown_inline',
            'make',
            'nginx',
            'php',
            'phpdoc',
            'powershell',
            'python',
            'razor',
            'regex',
            'rust',
            'scss',
            'sql',
            'swift',
            'toml',
            'tsx',
            'typescript',
            'vim',
            'vimdoc',
            'vue',
            'xml',
            'yaml',
            'zsh',
        })

        vim.api.nvim_create_autocmd('FileType', {
            callback = function(args)
                local lang = vim.treesitter.language.get_lang(vim.bo[args.buf].filetype)

                if lang then
                    pcall(vim.treesitter.start, args.buf, lang)
                end
            end,
        })
    end,
}
